setwd("/Users/kaylacoffman/Desktop/Evolution/Tasks/Task_07")
datak <- read.table("C:/Task_07/ebd_US-AL-101_202103_202103_relMar-2021.txt")
datak <- read.table("ebd_US-AL-101_202103_202103_relMar-2021.txt")
#this is data from eBird called "Basic Data Set (EBD)"
install.packages("readr")
library(readr)
datak <- read.table("ebd_US-AL-101_202103_202103_relMar-2021.txt", sep="\t")
spec()
head(datak)
install.packages("auk")
library(auk)
install.packages("rfishbase")
library(rfishbase)
species <- c("Callinectes sapidus", "Gadus morhua")
lh_data <- fishbase(dataset="species", species=species, level="species", cleaned=T)
fishbase(dataset, species, level = "species", cleaned = F, add_taxa = T)
#Another set of data (just for learning)
install.packages ("rvertnet")
library(rvertnet)
res <- searchbyterm(class="Aves", state= "West Virginia", limit=10, messages=FALSE)